<?php

namespace App\Models\Traits;

use Illuminate\Support\Str;

trait SlugCreating{

	protected static function bootSlugCreating()
	{
		/*Lorsque vous changez le nom de fonction boot en autres tels que :
			bootSlug : alors vous n'avez plus besoin d'appeler le fonction parent de boot comme parent::boot();
			Sinon vous aurez des erreurs */
		//parent::boot(); // TODO: Change the autogenerated stub

		static::creating(function($event_brote){
			$event_brote->slug=Str::slug($event_brote->titre);
		});
	}
}

